import { MatchType } from '../types';

export const simpleSmallSwiss: MatchType[] = [
  {
    id: 19753,
    nextMatchId: null,
    tournamentRoundText: '3',
    swissRoundNumber: 3,
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19754,
    nextMatchId: null,
    tournamentRoundText: '3',
    swissRoundNumber: 3,
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: '14754a1a-932c-4992-8dec-f7f94a339960',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'CoKe BoYz',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19755,
    nextMatchId: null,
    tournamentRoundText: '2',
    swissRoundNumber: 2,
    startTime: '2021-05-30',
    state: 'SCORE_DONE',
    participants: [
      {
        id: '14754a1a-932c-4992-8dec-f7f94a339960',
        resultText: 'Won',
        isWinner: true,
        status: 'PLAYED',
        name: 'CoKe BoYz',
        picture: 'teamlogos/client_team_default_logo',
      },
      {
        id: 'd16315d4-7f2d-427b-ae75-63a1ae82c0a8',
        resultText: 'Lost',
        isWinner: false,
        status: 'PLAYED',
        name: 'Aids Team',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19756,
    nextMatchId: null,
    tournamentRoundText: '2',
    swissRoundNumber: 2,
    startTime: '2021-05-30',
    state: 'RUNNING',
    participants: [
      {
        id: 'd8b9f00a-0ffa-4527-8316-da701894768e',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Art of kill',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
  {
    id: 19757,
    nextMatchId: null,
    tournamentRoundText: '1',
    swissRoundNumber: 1,
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 19758,
    nextMatchId: null,
    tournamentRoundText: '1',
    swissRoundNumber: 1,
    startTime: '2021-05-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: '9397971f-4b2f-44eb-a094-722eb286c59b',
        resultText: null,
        isWinner: false,
        status: null,
        name: 'Crazy Pepes',
        picture: 'teamlogos/client_team_default_logo',
      },
    ],
  },
];
